### ISSUE TITLE
consider being less aggressive with command aliasing

### ISSUE THREAD

**Issue by ee7** [crashappsec/chalk#12]
Supporting short command aliases means that the user can type less. But it also complicates adding commands that share a prefix with already-existing commands.

For example:

```console
$ chalk --no-color help insert | grep 'ins,'
  •  a̲l̲i̲a̲s̲e̲s̲ ̲ ̲: inject, ins, in, i
```

means that people will inevitably write scripts with `chalk i` ([Hyrum's Law](https://www.hyrumslaw.com/)), and get used to writing `chalk i`. So if chalk adds another command that begins with `i`, chalk must either make `chalk i`:

- An error, saying that it's ambiguous. I'd probably argue that this is a breaking change that requires a major version bump if chalk uses [semantic versioning](https://semver.org/), especially if chalk has not explicitly stated that a chalk update may break aliases.
- Work as before, but then the mapping of aliases to commands becomes complicated (`chalk f` continues to perform `chalk foo`, even when `f` is no longer an unambiguous prefix after `chalk frobnicate` is added).

Solutions:

1. State the contract somewhere. For example:
   - "a chalk update will never break an alias"
   - or "chalk makes no guarantees about aliases - scripts that use chalk should always use full chalk command names"
1. Alias less aggressively.

I would suggest the strong form of option 2. In my experience, aliases in CLI tools are not worth the increased complexity for maintenance and backward compatibility. I would suggest supporting only full command names, and delegating keystroke-saving to tab completion. `chalk i[Tab]` is only one keystroke more than `chalk i`.

Also, the current implementation of command aliasing does not support any unambiguous prefix. This makes it hard to remember which aliases are supported. For example, `chalk vers` is an alias for `chalk version`, but `chalk ver` isn't.

In other tools:

```console
$ git check
git: 'check' is not a git command. See 'git --help'.

The most similar command is
	checkout
```

```console
$ docker hist
docker: 'hist' is not a docker command.
See 'docker --help'
```

```console
$ gh var
unknown command "var" for "gh"

Did you mean this?
	pr
	variable
```

Chalk version: https://github.com/crashappsec/chalk/commit/ea36ce1c185731bba9ba191bc1a209a1da2bf6c1

**Comment by viega** [comment]
Yes,  good feedback, and the aliasing is even less important now that there's an autocompletion script. I think you're right and we should do in the other direction here, and probably delete all the aliases before the next release before it becomes too ingrained to delete them.

**Comment by viega** [comment]
I think flag aliasing is a bit more acceptable, as it's less about shortening names, and more about alternate names that are likely to be top of mind for people, but happy to take feedback on it.

Will open a PR removing command aliases in a few minutes, and I'm sure tomorrow will hear from more of the team if anyone has a strong counterpoint.

**Comment by viega** [comment]
None of the tests used aliases, so everything still passed locally. Taking this out of draft.
