### ISSUE TITLE
`hi.sh` script cannot be exec'd by chalk

### ISSUE THREAD

**Issue by indecisivedragon** [crashappsec/chalk#120]
## Description

running the `hi.sh` script given as an example in getting-started gives an exec error for chalk on main

## Impact

chalk should be able to wrap shell scripts without errors + this will be very confusing for new users working on the `getting-started` doc

## Steps to Reproduce

1. create a shell script `hi.sh` with the following instructions:
```
cat > hi.sh << EOF
sleep 10
echo ${@:-Hello, world}
EOF
chmod +x hi.sh
```
2. validate that the sh script is correct by running `./hi.sh` and then waiting 10s and seeing "hello world"
```
liming@liming-virtual-machine:~/workspace/chalk$ ./hi.sh 
Hello, world
```
3. run chalk with exec and observe error:
```
liming@liming-virtual-machine:~/workspace/chalk$ ./chalk exec --exec-command-name="./hi.sh"
error: Chalk: when execing '/home/liming/workspace/chalk/hi.sh': Exec format error
error: Chalk: when execing '/home/liming/workspace/chalk/hi.sh': Exec format error
error: Chalk: exec could not find a working executable to run.
```

**Comment by miki725** [comment]
looks like some shells do 🪄 to figure out what to execute when the script is without a shebang according to https://stackoverflow.com/questions/7268437/bash-script-execution-with-and-without-shebang-in-linux-and-bsd

not sure if that magic needs to be replicated in chalk....
