### ISSUE TITLE
chalk dump cache does not allow output to a file

### ISSUE THREAD

**Issue by indecisivedragon** [crashappsec/chalk#123]
## Description

Running `chalk dump aaa.tmp` will put the dump output to the `aaa.tmp` file, but attempting the same command with cache will result in the following error:
```
liming@system76-pc:~/workspace/chalk$ ./chalk dump cache aaa.tmp
error: chalk: When parsing command 'dump.cache': Too many arguments provided (max = 0)
```

## Impact

unable to store full config (not components) to output file for later examination, which we might want to use for tests etc.

## Steps to Reproduce
see above

**Comment by viega** [comment]
That's not a bug; it's something I chose not to do, because I didn't know what the semantics of that would even be. Do you dump a tar file?  Dump a bunch of individual files? 

If you want it all in one text file, just redirect stdout to a file.
