### ISSUE TITLE
CI: should run in draft PRs

### ISSUE THREAD

**Issue by ee7** [crashappsec/chalk#149]
## Description

Currently, we can only trigger tests for a PR after it is marked ready-for-review. There's a reasonable argument for that back when the chalk repo was private (which implies a limited number of free CI minutes), but the repo is now public, and runner minutes are free for public repos.

I propose making CI run tests on draft PRs.

## Impact

A chalk developer may mark a PR ready-for-review just to trigger CI, before the PR is actually ready for review. This may waste a reviewer's time.

## Steps to Reproduce

Create a draft PR and note that tests don't run.

**Comment by viega** [comment]
SGTM.

**Comment by miki725** [comment]
just fyi you can always trigger CI tests on any pushed branch manually without even having a PR
