### ISSUE TITLE
git: future tags should be annotated

### ISSUE THREAD

**Issue by ee7** [crashappsec/chalk#151]
Some previous tags in this repo are lightweight tags, which show up as "commit" below:

```console
$ git for-each-ref refs/tags
ab8ab0ea27305525483bc073b5775a151c7bc39a commit	refs/tags/v0.1.2
f9b8e22d63018f2197b46af018f4eb141a3f8577 commit	refs/tags/v0.1.3
403ff162b0da40a36b828d39b096599fe1c16d4d commit	refs/tags/v0.2.0
045c6e2d6f357040991d2dd165e92dabafc0b6b0 tag	refs/tags/v0.2.1
781dd00f0062e1d3a39d831c8db39d2967f84074 commit	refs/tags/v0.2.2
bbe9915be48016f6b9362ada796fbc71efcc4103 commit	refs/tags/v0.3.0
867fd3db5619abeb7e557ea123570351f0bdde39 tag	refs/tags/v0.3.1
```

The best practice is for release tags to be annotated tags. I've mentioned that, so the v0.3.1 tag is annotated and future ones will be too.

It is usually a bad idea to replace tags. There may be an argument for replacing the existing lightweight tags with annotated ones, but we shouldn't do that lightly. **Please don't try that without discussing with me.**

I have some well-used scripts to handle bumping versions and tagging releases, but I wouldn't say that automating tagging needs to be a priority right now. But automation can also help prevent e.g. accidentally tagging the wrong commit, or making a typo when writing the version number. It's easy to make little mistakes when trying to get a release out.

---

From `git tag --help`:

> Tag objects (created with `-a`, `-s`, or `-u`) are called "annotated" tags; they contain a creation date, the
> tagger name and e-mail, a tagging message, and an optional GnuPG signature. Whereas a "lightweight" tag is
> simply a name for an object (usually a commit object).
>
> Annotated tags are meant for release while lightweight tags are meant for private or temporary object labels.
> For this reason, some git commands for naming objects (like `git describe`) will ignore lightweight tags by
> default.

And from the [Pro Git book, on tagging](https://git-scm.com/book/en/v2/Git-Basics-Tagging):

>### Creating Tags
>Git supports two types of tags: **lightweight** and **annotated**.
>
>A lightweight tag is very much like a branch that doesn’t change — it’s just a pointer to a specific commit.
>
>Annotated tags, however, are stored as full objects in the Git database. They’re checksummed; contain the tagger name, email, and date; have a tagging message; and can be signed and verified with GNU Privacy Guard (GPG). It’s generally recommended that you create annotated tags so you can have all this information; but if you want a temporary tag or for some reason don’t want to keep the other information, lightweight tags are available too.

**Comment by miki725** [comment]
tag protection rule should enforce this now
