### ISSUE TITLE
chalk mark appears to contain incorrect `CHALK_VERSION`

### ISSUE THREAD

**Issue by ee7** [crashappsec/chalk#28]
### Example

With a binary `foo`, run:

```shell
chalk insert foo
strings foo | grep CHALK_VERSION | jq -r '.CHALK_VERSION,.INJECTOR_COMMIT_ID'
```

with Chalk version 175f32f001d90de02c3efa10d19467f08e98a1a7.

### Expected behavior

```text
0.1.2
175f32f001d90de02c3efa10d19467f08e98a1a7
```

### Observed behavior

```text
0.1.1
175f32f001d90de02c3efa10d19467f08e98a1a7
````

### Discussion

Maybe I'm missing something? But the Chalk version is reported as `0.1.2` when running `chalk version`:

```console
$ chalk version | head -n3
┏┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┳┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┓
┋ Chalk version ┋ 0.1.2                                    ┋
┋ Commit ID     ┋ 175f32f001d90de02c3efa10d19467f08e98a1a7 ┋
```

and all the versions are all the same in e.g. the [Getting Started - Chalk Insertion](https://crashoverride.com/docs/chalk/getting-started#chalk-insertion) example.

`CHALK_VERSION` is also different in `chalk.log`:

```console
$  jq < chalk.log | grep 'VERSION' 
        "CHALK_VERSION": "0.1.1",
    "INJECTOR_VERSION": "0.1.2",
    "_OP_CHALKER_VERSION": "0.1.2",
```

**Comment by viega** [comment]
Yes, thanks for finding this. We need to write a script that bumps the version everywhere in the sample place!
