### ISSUE TITLE
CLA ironically is a dead link

### ISSUE THREAD

**Issue by beef331** [crashappsec/chalk#3]
Clicking on the 'here' hyperlink takes one to:
https://crashoverride.com/docs/other/contrnuting

... an easy enough fix changing it to https://crashoverride.com/docs/other/contributing

Solves that, but then a lot of links on that page link to an unpublished repo.

**Comment by MyNameIsMeerkat** [comment]
Thanks for the contribution!

Issues fixed in PR #5  PR #6 

Appreciate you raising the issue 👍
