### ISSUE TITLE
Readme contains grammatical error

### ISSUE THREAD

**Issue by drjasonharrison** [crashappsec/chalk#35]
## Description

The readme contains "It make enterprise deployment easy" 

"make" and "deployment" should be plural. Unless you rewrite the sentence to be explicitly about a single enterprise deployment. 

## Impact

Minor 
## Steps to Reproduce

Read the readme.

**Comment by viega** [comment]
Thanks, @drjasonharrison! We appreciate you letting us know, and will get a fix up shortly.
