### ISSUE TITLE
chalk incorrectly handles empty commit message, and annotated tag with empty message

### ISSUE THREAD

**Issue by ee7** [crashappsec/chalk#353]
## Example

Create an annotated tag with an empty message, then report on it:

```text
git tag -a 1.2.3 -m ''
chalk insert foo
```

## Expected behavior

The operation is successful, and the chalk report contains tag-related keys.

## Observed behavior

Chalk outputs warnings, something like:

```text
warn:  unable to retrieve Git ref data: 3f1bbc7b19cee603a52c61eb42203cf60bdfcb7e due to: index -1 not in 0 .. 136
warn:  1.2.3: Git tag couldn't be loaded
```

and chalk report omits the tag-related keys.

## Other Information

The impact is just for annotated tags with an empty tag message. I believe that's a completely legitimate/supported thing to do (e.g. from a rationale of the tag message not being the best place to write things, and then not wanting to repeat yourself), but probably not extremely common.

Occurs with:

- The latest chalk release, 0.4.5
- The latest commit on `main`, https://github.com/crashappsec/chalk/commit/482b0ed0e92b3bb75d8439cd11eeb5115d592b95
- The latest commit on https://github.com/crashappsec/chalk/pull/351 (https://github.com/crashappsec/chalk/pull/351/commits/b000be9cd7fd189ddf3c487d4f650dd47a6d7f11)

**Comment by miki725** [comment]
can commit messages be empty as well? if so we might might have similar issue there as well
