### ISSUE TITLE
Broken links to the demo-* c4ms in chalkdust.io

### ISSUE THREAD

**Issue by bureado** [crashappsec/chalk#40]
## Description

On https://crashoverride.com/docs/chalk/getting-started, `chalk load` on `https://chalkdust.io/demo-[wrap|http|docker].c4m` is mentioned, but those `403`.

Other `c4m` files mentioned in the docs, which happen to be the ones in the `configs` folder, can be downloaded from `chalkdust.io` without issues.

## Impact

Someone following the _Getting started_ guide might not be able to get to the specific scenarios when doing `chalk load`.

## Steps to Reproduce

When starting the https://crashoverride.com/docs/chalk/getting-started#sending-the-data-somewhere section of Getting started, get the following (possibly unhandled) error when `chalk load`:

```
root@5b45d6954dca:/# chalk load https://chalkdust.io/demo-http.c4m
info:  Installed bash auto-completion file to: /root/.local/share/bash_completion/completions/chalk.bash
info:  Added sourcing of autocomplete to ~/.bash_completion file
info:  Script should be sourced automatically on your next login.
info:  https://chalkdust.io/demo-http.c4m: Validating configuration.
warn:  Note: validation involves creating a new configuration context and evaluating your code to make sure it at least evaluates fine on a default path.  subscribe() and
       unsubscribe() will ignore any calls, but if your config always shells out, it will happen here.  To skip error checking, you can add --no-validation.  But, if there's a basic error,
       chalk may not run without passing --no-use-embedded-config.  Suppress this message in the future by setting `no_validation_warning` in the config, or passing
       --no-validation-warning on the command line.
error:

chalkhttps://chalkdust.io/demo-http.c4m:
1:2: Invalid character found
  <?xml version="1.0" encoding="UTF-8"?>


^
```

**Comment by viega** [comment]
Thanks, that's embarrassing; we updated the guide from the preview release but clearly missed migrating those links. We'll get on it really soon.

**Comment by viega** [comment]
This is fixed. Thanks very, very much @bureado !
