### ISSUE TITLE
bug: loading an invalid composable config breaks chalk

### ISSUE THREAD

**Issue by indecisivedragon** [crashappsec/chalk#66]
## Description

Loading first a valid config, and then an invalid composable config where the `use` directive points to a file that doesn't exist will pass `chalk load` validation for a chalk binary, but then any invocation of chalk will be broken forever because of config errors. 

Tested on main and `jtv/releaseitems`, commit 03227cc0fe0b92b3f8a7e435c909c92e370ecf10, and occurring in both.

## Impact

Recovery with `./chalk --no-use-embedded-config load default` will work. However it's pretty annoying to run into this if you add a line to a config and misspell something.

## Steps to Reproduce

1. ensure you have a newly-built binary by `rm ./chalk` and `make chalk` so that the default config is loaded (optional -- this is just for safety)
2. ensure the DEFAULT config is loaded by checking `chalk dump`:
```
liming@liming-virtual-machine:~/workspace/chalk$ ./chalk dump
# The default config is empty. Please see chalk documentation for examples.
```
3. create a valid config, such as `sample.c4m` (in root of chalk repository for example):
```
# exec heartbeat
exec.heartbeat: true
exec.heartbeat_rate: <<1 seconds>>
```
4. load the valid config with `./chalk load ./sample.c4m` and watch it pass without errors:
```
liming@liming-virtual-machine:~/workspace/chalk$ ./chalk load ./sample.c4m
info:  Attempting to load module from: /home/liming/workspace/chalk/sample.c4m
                                 CONFIGURING COMPONENT: /HOME/LIMING/WORKSPACE/CHALK/SAMPLE                                  
                               FINISHED CONFIGURATION FOR /HOME/LIMING/WORKSPACE/CHALK/SAMPLE                                

info:  /home/liming/workspace/chalk/sample.c4m: Validating configuration.
info:  /home/liming/workspace/chalk/sample.c4m: Configuration successfully validated.
info:  Configuration replaced in binary: /home/liming/workspace/chalk/chalk
```
5. ensure that the config has been loaded by checking `./chalk dump`:
```
liming@liming-virtual-machine:~/workspace/chalk$ ./chalk dump

use sample from "/home/liming/workspace/chalk"
```
6. IN THE SAME CONFIG FILE `sample.c4m`, amend to this invalid config:
```
# exec heartbeat
exec.heartbeat: true
exec.heartbeat_rate: <<10 seconds>>

use aaa from "./tests/data/configs/profiles"
```
where `aaa` is a file that doesn't exist, but the path `"./tests/data/configs/profiles"` points to a directory that does exist
7. reload the sample config with `./chalk load ./sample.c4m` and observe that it validates without errors:
```
info:  Attempting to load module from: /home/liming/workspace/chalk/sample.c4m
                                 CONFIGURING COMPONENT: /HOME/LIMING/WORKSPACE/CHALK/SAMPLE                                  
                               FINISHED CONFIGURATION FOR /HOME/LIMING/WORKSPACE/CHALK/SAMPLE                                

info:  Configuration replaced in binary: /home/liming/workspace/chalk/chalk
```
8. running any chalk command will give a config validation error:
```
liming@liming-virtual-machine:~/workspace/chalk$ ./chalk env
error:  Could not retrieve needed source file: /home/liming/workspace/chalk/tests/data/configs/profiles/aaa.c4m
error:  Could not load configuration files. exiting.
```

**Comment by viega** [comment]
I thought I closed this as complete, did I not? Or was there a second issue that I confused with this one?  Anyway, this one is definitely done, and will give:
```
error:  Could not retrieve needed source file: /Users/viega/dev/chalk/tests/data/configs/profiles/aaa.c4m
```
