### ISSUE TITLE
docker entrypoint wrapping does not preserve all command args

### ISSUE THREAD

**Issue by miki725** [crashappsec/chalk#70]
## Description

When wrapping docker container and an `ENTRYPOINT`/`CMD` has any named arguments, chalk would not preserve them fully.

For example:

```dockerfile
FROM alpine
ENTRYPOINT ["ls", "-la"]
```

wrapped container would have:

```dockerfile
ENTRYPOINT ["/chalk","exec","--exec-command-name","ls","-la"]
```

however at execution it would not work:

```
error:  chalk: When parsing command 'exec': --l: Invalid choice: 'a'
```

Similarly it would not work if the `ENTRYPOINT`/`CMD` is a string vs an array of args:

```dockerfile
FROM alpine
ENTRYPOINT ls -la"
```

## Impact

Any dockerfile defining custom entrypoint/command with named argument might not be able to run

## Steps to Reproduce

```sh
./chalk --config-file=configs/wrap_entrypoints.c4m --trace docker build /tmp -t test -f <(echo -e 'FROM busybox\nENTRYPOINT ["ls", "-la"]')
docker inspect test | jq '.[].Config.Entrypoint'
docker run --rm test
```

**Comment by viega** [comment]
Fixed in #67
