### ISSUE TITLE
reloading config from remote keeps accumulating

### ISSUE THREAD

**Issue by indecisivedragon** [crashappsec/chalk#74]
## Description

Loading a config from remote, ex running `./chalk load https://chalkdust.io/app_inventory.c4m` 3 times, results in the following output on `./chalk dump`:
```
liming@system76-pc:~/workspace/chalk$ ./chalk dump
                                                                                                                         
use app_inventory from "https://chalkdust.io"                                                                            
use app_inventory from "https://chalkdust.io"                                                                            
use app_inventory from "https://chalkdust.io"   
```

## Impact

This is confusing as I would expect `app_inventory` to be only loaded once from the same place (ex: updating it if there was a change to remote) instead of the same thing loaded three times. Also it's not clear if the same output will be tripled.

## Steps to Reproduce

see description

**Comment by viega** [comment]
Yes, this is the thing I was talking about that I knew there was a bug, but
didn't have time to fix it before the release. It's supposed to detect the
module is already imported somewhere and reconfigure only, and it wasn't
obvious why that was all not working. I'll take this, but I'm not going to
get to it for a while. The other one I'll be on today.
