### ISSUE TITLE
Hidden characters after running chalk help in tmux session

### ISSUE THREAD

**Issue by nettrino** [crashappsec/chalk#96]
## Description

In a tmux pane, after running `chalk help`, any subsequent commands are not printed. For instance, in the screenshot below, I compiled chalk and run `chalk help`, followed by `ls`. As seen, `ls` executed fine but the actual text was not printed on the terminal.

Env info:
```
TERM_PROGRAM_VERSION=3.3a
TERM=screen-256color
TERM_PROGRAM=tmux
```
<img width="1512" alt="Screenshot 2023-11-13 at 11 46 24 PM" src="https://github.com/crashappsec/chalk/assets/4614044/1c2af23b-91e4-40b5-b978-a997cd86f821">

**Comment by nettrino** [comment]
Correct - does not happen if color is off, will look into it further and post details here for visibility

**Comment by nettrino** [comment]
@viega actually I take that back. I just got back to this, and I logged in again via`ssh` to a remote machine and then run `./chalk --no-color help` even without tmux and still getting hidden chars
![Screenshot 2023-11-28 at 12 24 49 AM](https://github.com/crashappsec/chalk/assets/4614044/8d13140e-efe9-4b1e-8292-17eae2fccf3f)

**Comment by miki725** [comment]
upstream fix was merged in other PR so closing
