### ISSUE TITLE
The command "chalk load https://chalkdust.io/demo-http.c4m" is not working

### ISSUE THREAD

**Issue by danielmakhovskyicrashoverride** [crashappsec/chalk#97]
## Description

After putting the command "chalk load https://chalkdust.io/demo-http.c4m" in the terminal, an error appears

## Impact

Can't proceed with the installation

## Steps to Reproduce

1.Go step by step as written in the documentation https://crashoverride.com/docs/chalk/getting-started to the "Please Note - it does NOT run in the background, so you should either start a second shell, or manually background the server process. Starting in a separate shell is recommended so that you can observe the server output." section
2.Type a command - chalk load https://chalkdust.io/demo-http.c4m
3.Click "Enter"
4.Pay attention to the result

AR: The error message appears
ER: All works fine and I am able to continue with the installation

## Other Information

https://monosnap.com/file/F660aGz2zvg51kKx1AkQK31OJqHOS1

**Comment by viega** [comment]
It should not work due to recent changes; the documentation should be updated. File names must be valid identifiers, plus the extension.
